include:
  - project: 'alanpeng/kubeadm-version'
    file: '/gitlab-ci-template.yml'

variables:
# remove comment (or set variable in Settings) to build with BUILDX
# CI_BUILDX_ARCHS: "linux/arm/v7"
  CI_BUILD_ARM64: "enabled"
