jobs:
  build-branches-aarch64:
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            docker login -u $AlibabaDOCKER_USERNAME -p $AlibabaDOCKER_PASSWORD
            ${PWD}/pull-images.sh

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-aarch64

