jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            docker build -t wise2c/kubeadm-version:$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/kubeadm-version:$CIRCLE_TAG
            docker run --rm --name=kubeadm-version wise2c/kubeadm-version:$CIRCLE_TAG kubeadm config images list

workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
