version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            docker build -t wise2c/kubeadm-version:$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/kubeadm-version:$CIRCLE_BRANCH
            docker run --rm --name=kubeadm-version wise2c/kubeadm-version:$CIRCLE_BRANCH kubeadm config images list

workflows:
  build-and-release:
    jobs:
      #--------------- BUILD ---------------#
      - build:
          name: build v1.26.0
          version: v1.26.0
          filters:
            tags:
              only: /^v.*/

      #--------------- DEPLOY ---------------#
      - release:
          name: release
          requires:
            - build v1.26.0
